---
- hosts: localhost
  tasks:
  - name: "Making directory"
    shell: "mkdir -p {{app_dir}}/logs {{app_dir}}/minecraft"
  - name: "Create eula.txt"
    copy:
      dest: "{{app_dir}}/minecraft/eula.txt"
      content: |
        eula=true
  - name: "Create eula.txt"
    copy:
      dest: "{{app_dir}}/minecraft/server.properties"
      content: |
        server-port=3074
        rcon.port=8080
        query.port=3074
        rcon.password=Crafter9000
        enable-rcon=true
        level-name=world
        motd=Welcome to TheGreatSt0rm Git Automated Server!
        max-players=20
        level-seed=2976643220357667859
  - name: "Downloading minecraft"
    get_url:
      url: https://launcher.mojang.com/v1/objects/c8f83c5655308435b3dcf03c06d9fe8740a77469/server.jar
      dest: "{{app_dir}}/minecraft/server.jar"
      mode: '0750'



