---
- hosts: localhost
  tasks:
  - name: "Remove Minecraft old file"
    shell: "rm -rf {{app_dir}}/minecraft/server.jar"
  - name: "Reinstalling minecraft"
    get_url:
      url: https://launcher.mojang.com/v1/objects/c8f83c5655308435b3dcf03c06d9fe8740a77469/server.jar
      dest: "{{app_dir}}/minecraft/server.jar"
      mode: '0750'



